---
- hosts: group
  become: yes
  tasks:
    - name: "Install Nginx"
      ansible.builtin.apt:
        name: nginx
        state: latest
        cache_valid_time: 86400
        update_cache: yes
    - name: "Start Nginx"
      service:
        name: nginx
        state: started
